In [3]:
import pandas as pd
import numpy as np
import csv
df=pd.read_csv('Crime_Data_From_2010_to_Present.csv')
df.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
0,1208575,03/14/2013,03/11/2013,1800,12,77th Street,1241,626,INTIMATE PARTNER - SIMPLE ASSAULT,0416 0446 1243 2000,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,626.0,NaN,NaN,NaN,6300 BRYNHURST AV,NaN,"(33.9829, -118.3338)"
1,102005556,01/25/2010,01/22/2010,2300,20,Olympic,2071,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,VAN NESS,15TH,"(34.0454, -118.3157)"
2,418,03/19/2013,03/18/2013,2030,18,Southeast,1823,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E 104TH ST,NaN,"(33.942, -118.2717)"
3,101822289,11/11/2010,11/10/2010,1800,18,Southeast,1803,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,88TH,WALL,"(33.9572, -118.2717)"
4,42104479,01/11/2014,01/04/2014,2300,21,Topanga,2133,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329,...,NaN,IC,Invest Cont,745.0,NaN,NaN,NaN,7200 CIRRUS WY,NaN,"(34.2009, -118.6369)"

In [19]:
import datetime
dates = pd.DatetimeIndex(df['Date Occurred'])

df['Year'],df['Month']=dates.year,dates.month
df.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,Year,Month
0,1208575,03/14/2013,03/11/2013,1800,12,77th Street,1241,626,INTIMATE PARTNER - SIMPLE ASSAULT,0416 0446 1243 2000,...,Adult Other,626.0,NaN,NaN,NaN,6300 BRYNHURST AV,NaN,"(33.9829, -118.3338)",2013,3
1,102005556,01/25/2010,01/22/2010,2300,20,Olympic,2071,510,VEHICLE - STOLEN,NaN,...,Invest Cont,510.0,NaN,NaN,NaN,VAN NESS,15TH,"(34.0454, -118.3157)",2010,1
2,418,03/19/2013,03/18/2013,2030,18,Southeast,1823,510,VEHICLE - STOLEN,NaN,...,Invest Cont,510.0,NaN,NaN,NaN,200 E 104TH ST,NaN,"(33.942, -118.2717)",2013,3
3,101822289,11/11/2010,11/10/2010,1800,18,Southeast,1803,510,VEHICLE - STOLEN,NaN,...,Invest Cont,510.0,NaN,NaN,NaN,88TH,WALL,"(33.9572, -118.2717)",2010,11
4,42104479,01/11/2014,01/04/2014,2300,21,Topanga,2133,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329,...,Invest Cont,745.0,NaN,NaN,NaN,7200 CIRRUS WY,NaN,"(34.2009, -118.6369)",2014,1

In [8]:
df['Time Occurred'].describe()

count    1.552960e+06
mean     1.364355e+03
std      6.465544e+02
min      1.000000e+00
25%      9.300000e+02
50%      1.430000e+03
75%      1.900000e+03
max      2.359000e+03
Name: Time Occurred, dtype: float64

In [48]:
df1=df[['Year','Time Occurred','Crime Code Description']]

df1['Count']=1
df1

C:\Users\hp\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

,Year,Time Occurred,Crime Code Description,Count
0,2013,1800,INTIMATE PARTNER - SIMPLE ASSAULT,1
1,2010,2300,VEHICLE - STOLEN,1
2,2013,2030,VEHICLE - STOLEN,1
3,2010,1800,VEHICLE - STOLEN,1
4,2014,2300,VANDALISM - MISDEAMEANOR ($399 OR UNDER),1
5,2013,1400,CRIMINAL HOMICIDE,1
6,2010,2230,VEHICLE - STOLEN,1
7,2010,1600,VEHICLE - STOLEN,1
8,2010,1600,VEHICLE - STOLEN,1
9,2013,800,"EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)",1
10,2010,2100,VEHICLE - STOLEN,1
11,2010,1315,VEHICLE - STOLEN,1
12,2013,1200,THEFT PLAIN - PETTY ($950 & UNDER),1
13,2013,1200,STALKING,1
14,2013,2030,SHOPLIFTING - PETTY THEFT ($950 & UNDER),1
15,2013,500,INTIMATE PARTNER - SIMPLE ASSAULT,1
16,2013,1420,BATTERY - SIMPLE ASSAULT,1
17,2013,1430,INTIMATE PARTNER - SIMPLE ASSAULT,1
18,2013,1500,BATTERY - SIMPLE ASSAULT,1
19,2013,1730,"EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)",1
20,2013,100,INTIMATE PARTNER - SIMPLE ASSAULT,1
21,2013,2200,DOCUMENT FORGERY / STOLEN FELONY,1
22,2013,1600,INTIMATE PARTNER - SIMPLE ASSAULT,1
23,2013,2010,BATTERY - SIMPLE ASSAULT,1
24,2013,2315,BATTERY - SIMPLE ASSAULT,1
25,2013,1120,INTIMATE PARTNER - SIMPLE ASSAULT,1
26,2010,1230,VEHICLE - STOLEN,1
27,2013,1630,BIKE - STOLEN,1
28,2013,1815,ROBBERY,1
29,2013,1930,INTIMATE PARTNER - SIMPLE ASSAULT,1
...,...,...,...,...
1552930,2017,217,ARSON,1
1552931,2017,330,KIDNAPPING,1
1552932,2017,800,THEFT OF IDENTITY,1
1552933,2017,945,BURGLARY,1
1552934,2017,2000,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1
1552935,2017,2015,THEFT PLAIN - PETTY ($950 & UNDER),1
1552936,2017,2000,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),1
1552937,2017,2250,OTHER MISCELLANEOUS CRIME,1
1552938,2017,1600,BURGLARY,1
1552939,2017,1200,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),1
1552940,2017,1600,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1
1552941,2017,330,INTIMATE PARTNER - SIMPLE ASSAULT,1
1552942,2017,2012,SHOPLIFTING - PETTY THEFT ($950 & UNDER),1
1552943,2017,2030,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1
1552944,2017,2000,CHILD STEALING,1
1552945,2017,730,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),1
1552946,2017,1230,SHOPLIFTING - PETTY THEFT ($950 & UNDER),1
1552947,2017,1730,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1
1552948,2017,1300,"LETTERS, LEWD",1
1552949,2017,1440,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),1
1552950,2017,930,BATTERY - SIMPLE ASSAULT,1
1552951,2017,1915,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",1
1552952,2017,2350,BATTERY - SIMPLE ASSAULT,1
1552953,2017,720,BATTERY - SIMPLE ASSAULT,1
1552954,2017,720,BATTERY - SIMPLE ASSAULT,1
1552955,2017,1,THEFT OF IDENTITY,1
1552956,2017,2030,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1
1552957,2017,800,BATTERY - SIMPLE ASSAULT,1
1552958,2016,200,OTHER MISCELLANEOUS CRIME,1
1552959,2017,1600,THEFT OF IDENTITY,1

In [32]:
df1.to_csv('Crime_Data.csv',encoding='utf-8')

In [41]:
df2=df1[df1['Year']==2017].head(500)
df2.head()

,Year,Month,Date Occurred,Time Occurred,Crime Code Description,Count
622128,2017,7,07/21/2017,1700,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1
625455,2017,7,07/21/2017,1415,BURGLARY,1
626499,2017,7,07/21/2017,1800,BURGLARY,1
640441,2017,7,07/17/2017,1800,VEHICLE - STOLEN,1
640712,2017,7,07/21/2017,1500,BIKE - STOLEN,1

In [42]:
df2.to_csv('Crime_Data_500.csv',encoding='utf-8')

In [51]:
df3=df1.groupby(['Year','Time Occurred','Crime Code Description']).sum()
df3

                                                                       Count
Year Time Occurred Crime Code Description
2010 1             ARSON                                                   1
                   ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT         66
                   ATTEMPTED ROBBERY                                      12
                   BATTERY - SIMPLE ASSAULT                              138
                   BATTERY ON A FIREFIGHTER                                2
                   BATTERY WITH SEXUAL CONTACT                            28
                   BIKE - STOLEN                                           4
                   BRANDISH WEAPON                                         3
                   BUNCO, GRAND THEFT                                      3
                   BURGLARY                                              154
                   BURGLARY FROM VEHICLE                                 264
                   BURGLARY FROM VEHICLE, ATTEMPTED                        5
                   BURGLARY, ATTEMPTED                                     9
                   CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT             5
                   CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT                20
                   CHILD ANNOYING (17YRS & UNDER)                         15
                   CHILD NEGLECT (SEE 300 W.I.C.)                         29
                   CHILD STEALING                                          3
                   CONSPIRACY                                              1
                   CONTRIBUTING                                            1
                   COUNTERFEIT                                             1
                   CREDIT CARDS, FRAUD USE ($950.01 & OVER)                4
                   CRIMINAL HOMICIDE                                       3
                   CRIMINAL THREATS - NO WEAPON DISPLAYED                 54
                   CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 Y...    105
                   CRUELTY TO ANIMALS                                      4
                   DEFRAUDING INNKEEPER/THEFT OF SERVICES, $400 & ...      2
                   DISCHARGE FIREARMS/SHOTS FIRED                          1
                   DISTURBING THE PEACE                                    5
                   DOCUMENT FORGERY / STOLEN FELONY                      140
...                                                                      ...
2017 2355          VIOLATION OF COURT ORDER                                1
     2356          BATTERY - SIMPLE ASSAULT                                1
                   BURGLARY                                                1
                   LETTERS, LEWD                                           1
                   VANDALISM - FELONY ($400 & OVER, ALL CHURCH VAN...      1
     2357          ARSON                                                   1
                   BATTERY - SIMPLE ASSAULT                                1
                   EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)              1
                   THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)         1
     2358          ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER            1
                   THEFT PLAIN - PETTY ($950 & UNDER)                      1
                   VANDALISM - FELONY ($400 & OVER, ALL CHURCH VAN...      2
                   VEHICLE - STOLEN                                        1
     2359          BATTERY - SIMPLE ASSAULT                                5
                   BIKE - STOLEN                                           1
                   BURGLARY                                                3
                   BURGLARY FROM VEHICLE                                   6
                   DOCUMENT FORGERY / STOLEN FELONY                        2
                   INTIMATE PARTNER - SIMPLE ASSAULT                       2
                   OTHER MISCELLANEOUS CRIME                               2
                   ROBBERY                                                 2
                   THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)        2
                   THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)         4
                   THEFT OF IDENTITY                                       5
                   THEFT PLAIN - PETTY ($950 & UNDER)                      6
                   THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIV...      3
                   VANDALISM - FELONY ($400 & OVER, ALL CHURCH VAN...      7
                   VANDALISM - MISDEAMEANOR ($399 OR UNDER)                3
                   VEHICLE - STOLEN                                       11
                   VIOLATION OF RESTRAINING ORDER                          1

[129837 rows x 1 columns]

In [52]:
df3.to_csv('Crime_Data_Summary.csv',encoding='utf-8')

In [55]:
df4=pd.read_csv('Crime_Data_Summary.csv')
df4.head()

   Year  Time Occurred                          Crime Code Description  Count
0  2010              1                                           ARSON      1
1  2010              1  ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT     66
2  2010              1                               ATTEMPTED ROBBERY     12
3  2010              1                        BATTERY - SIMPLE ASSAULT    138
4  2010              1                        BATTERY ON A FIREFIGHTER      2

In [77]:
len(df4)

129837

In [92]:
crime=["BATTERY - SIMPLE ASSAULT","BURGLARY FROM VEHICLE","VEHICLE - STOLEN","BURGLARY","THEFT OF IDENTITY"]

In [107]:
df5=df4[df4['Crime Code Description'].isin(crime)]
df5=df5[df5['Year'].isin([2014,2015,2016])]  
df5

        Year  Time Occurred    Crime Code Description  Count   Hour
60735   2014              1  BATTERY - SIMPLE ASSAULT    110   0.01
60744   2014              1                  BURGLARY    123   0.01
60745   2014              1     BURGLARY FROM VEHICLE    198   0.01
60795   2014              1         THEFT OF IDENTITY    989   0.01
60805   2014              1          VEHICLE - STOLEN    167   0.01
60809   2014              2  BATTERY - SIMPLE ASSAULT      1   0.02
60810   2014              2                  BURGLARY      1   0.02
60816   2014              2         THEFT OF IDENTITY      1   0.02
60819   2014              3                  BURGLARY      1   0.03
60820   2014              3     BURGLARY FROM VEHICLE      1   0.03
60827   2014              4  BATTERY - SIMPLE ASSAULT      1   0.04
60828   2014              4                  BURGLARY      1   0.04
60835   2014              5  BATTERY - SIMPLE ASSAULT     70   0.05
60842   2014              5                  BURGLARY     34   0.05
60843   2014              5     BURGLARY FROM VEHICLE     89   0.05
60882   2014              5         THEFT OF IDENTITY    272   0.05
60891   2014              5          VEHICLE - STOLEN     90   0.05
60905   2014              9  BATTERY - SIMPLE ASSAULT      1   0.09
60906   2014              9                  BURGLARY      1   0.09
60910   2014             10  BATTERY - SIMPLE ASSAULT     50   0.10
60915   2014             10                  BURGLARY     12   0.10
60916   2014             10     BURGLARY FROM VEHICLE     30   0.10
60944   2014             10         THEFT OF IDENTITY      9   0.10
60952   2014             10          VEHICLE - STOLEN     22   0.10
60955   2014             11                  BURGLARY      1   0.11
60963   2014             13                  BURGLARY      1   0.13
60964   2014             13     BURGLARY FROM VEHICLE      1   0.13
60970   2014             14                  BURGLARY      1   0.14
60975   2014             15  BATTERY - SIMPLE ASSAULT     48   0.15
60980   2014             15                  BURGLARY     22   0.15
...      ...            ...                       ...    ...    ...
114699  2016           2345  BATTERY - SIMPLE ASSAULT     58  23.45
114704  2016           2345                  BURGLARY     29  23.45
114705  2016           2345     BURGLARY FROM VEHICLE     47  23.45
114740  2016           2345         THEFT OF IDENTITY     21  23.45
114750  2016           2345          VEHICLE - STOLEN     50  23.45
114762  2016           2346         THEFT OF IDENTITY      1  23.46
114763  2016           2347                  BURGLARY      1  23.47
114772  2016           2349         THEFT OF IDENTITY      1  23.49
114776  2016           2350  BATTERY - SIMPLE ASSAULT     43  23.50
114781  2016           2350                  BURGLARY     20  23.50
114782  2016           2350     BURGLARY FROM VEHICLE     22  23.50
114809  2016           2350         THEFT OF IDENTITY      4  23.50
114818  2016           2350          VEHICLE - STOLEN     38  23.50
114821  2016           2351                  BURGLARY      1  23.51
114826  2016           2352         THEFT OF IDENTITY      1  23.52
114829  2016           2353                  BURGLARY      3  23.53
114832  2016           2354                  BURGLARY      1  23.54
114839  2016           2355  BATTERY - SIMPLE ASSAULT     21  23.55
114843  2016           2355                  BURGLARY      7  23.55
114844  2016           2355     BURGLARY FROM VEHICLE     43  23.55
114871  2016           2355         THEFT OF IDENTITY      5  23.55
114880  2016           2355          VEHICLE - STOLEN     44  23.55
114884  2016           2356  BATTERY - SIMPLE ASSAULT      1  23.56
114885  2016           2356                  BURGLARY      2  23.56
114892  2016           2357         THEFT OF IDENTITY      1  23.57
114899  2016           2359  BATTERY - SIMPLE ASSAULT      7  23.59
114903  2016           2359                  BURGLARY      6  23.59
114904  2016           2359     BURGLARY FROM VEHICLE     19  23.59
114921  2016           2359         THEFT OF IDENTITY     11  23.59
114927  2016           2359          VEHICLE - STOLEN     22  23.59

[7273 rows x 5 columns]

In [108]:
df5.to_csv('Crime_Data_Top5.csv')

In [133]:
from datetime import * 

def convert_to_time(t):
    second=0
    if len(t)==4:
        hour=int(t[:2])
        minute=int(t[3:])
    elif len(t)>=3:
        hour=int(t[0])
        minute=int(t[1:])
    else:
        hour=0
        minute=int(t)
    new_time = time(hour,minute,second)
    return new_time
print convert_to_time('1800')

18:00:00

In [135]:
#df5['Time Occurred']=df5['Time Occurred'].astype('string').apply(convert_to_time)
df5['Time Occurred']

60735     00:01:00
60744     00:01:00
60745     00:01:00
60795     00:01:00
60805     00:01:00
60809     00:02:00
60810     00:02:00
60816     00:02:00
60819     00:03:00
60820     00:03:00
60827     00:04:00
60828     00:04:00
60835     00:05:00
60842     00:05:00
60843     00:05:00
60882     00:05:00
60891     00:05:00
60905     00:09:00
60906     00:09:00
60910     00:10:00
60915     00:10:00
60916     00:10:00
60944     00:10:00
60952     00:10:00
60955     00:11:00
60963     00:13:00
60964     00:13:00
60970     00:14:00
60975     00:15:00
60980     00:15:00
            ...
114699    23:05:00
114704    23:05:00
114705    23:05:00
114740    23:05:00
114750    23:05:00
114762    23:06:00
114763    23:07:00
114772    23:09:00
114776    23:00:00
114781    23:00:00
114782    23:00:00
114809    23:00:00
114818    23:00:00
114821    23:01:00
114826    23:02:00
114829    23:03:00
114832    23:04:00
114839    23:05:00
114843    23:05:00
114844    23:05:00
114871    23:05:00
114880    23:05:00
114884    23:06:00
114885    23:06:00
114892    23:07:00
114899    23:09:00
114903    23:09:00
114904    23:09:00
114921    23:09:00
114927    23:09:00
Name: Time Occurred, dtype: object

In [136]:
df5

        Year Time Occurred    Crime Code Description  Count   Hour
60735   2014      00:01:00  BATTERY - SIMPLE ASSAULT    110   0.01
60744   2014      00:01:00                  BURGLARY    123   0.01
60745   2014      00:01:00     BURGLARY FROM VEHICLE    198   0.01
60795   2014      00:01:00         THEFT OF IDENTITY    989   0.01
60805   2014      00:01:00          VEHICLE - STOLEN    167   0.01
60809   2014      00:02:00  BATTERY - SIMPLE ASSAULT      1   0.02
60810   2014      00:02:00                  BURGLARY      1   0.02
60816   2014      00:02:00         THEFT OF IDENTITY      1   0.02
60819   2014      00:03:00                  BURGLARY      1   0.03
60820   2014      00:03:00     BURGLARY FROM VEHICLE      1   0.03
60827   2014      00:04:00  BATTERY - SIMPLE ASSAULT      1   0.04
60828   2014      00:04:00                  BURGLARY      1   0.04
60835   2014      00:05:00  BATTERY - SIMPLE ASSAULT     70   0.05
60842   2014      00:05:00                  BURGLARY     34   0.05
60843   2014      00:05:00     BURGLARY FROM VEHICLE     89   0.05
60882   2014      00:05:00         THEFT OF IDENTITY    272   0.05
60891   2014      00:05:00          VEHICLE - STOLEN     90   0.05
60905   2014      00:09:00  BATTERY - SIMPLE ASSAULT      1   0.09
60906   2014      00:09:00                  BURGLARY      1   0.09
60910   2014      00:10:00  BATTERY - SIMPLE ASSAULT     50   0.10
60915   2014      00:10:00                  BURGLARY     12   0.10
60916   2014      00:10:00     BURGLARY FROM VEHICLE     30   0.10
60944   2014      00:10:00         THEFT OF IDENTITY      9   0.10
60952   2014      00:10:00          VEHICLE - STOLEN     22   0.10
60955   2014      00:11:00                  BURGLARY      1   0.11
60963   2014      00:13:00                  BURGLARY      1   0.13
60964   2014      00:13:00     BURGLARY FROM VEHICLE      1   0.13
60970   2014      00:14:00                  BURGLARY      1   0.14
60975   2014      00:15:00  BATTERY - SIMPLE ASSAULT     48   0.15
60980   2014      00:15:00                  BURGLARY     22   0.15
...      ...           ...                       ...    ...    ...
114699  2016      23:05:00  BATTERY - SIMPLE ASSAULT     58  23.45
114704  2016      23:05:00                  BURGLARY     29  23.45
114705  2016      23:05:00     BURGLARY FROM VEHICLE     47  23.45
114740  2016      23:05:00         THEFT OF IDENTITY     21  23.45
114750  2016      23:05:00          VEHICLE - STOLEN     50  23.45
114762  2016      23:06:00         THEFT OF IDENTITY      1  23.46
114763  2016      23:07:00                  BURGLARY      1  23.47
114772  2016      23:09:00         THEFT OF IDENTITY      1  23.49
114776  2016      23:00:00  BATTERY - SIMPLE ASSAULT     43  23.50
114781  2016      23:00:00                  BURGLARY     20  23.50
114782  2016      23:00:00     BURGLARY FROM VEHICLE     22  23.50
114809  2016      23:00:00         THEFT OF IDENTITY      4  23.50
114818  2016      23:00:00          VEHICLE - STOLEN     38  23.50
114821  2016      23:01:00                  BURGLARY      1  23.51
114826  2016      23:02:00         THEFT OF IDENTITY      1  23.52
114829  2016      23:03:00                  BURGLARY      3  23.53
114832  2016      23:04:00                  BURGLARY      1  23.54
114839  2016      23:05:00  BATTERY - SIMPLE ASSAULT     21  23.55
114843  2016      23:05:00                  BURGLARY      7  23.55
114844  2016      23:05:00     BURGLARY FROM VEHICLE     43  23.55
114871  2016      23:05:00         THEFT OF IDENTITY      5  23.55
114880  2016      23:05:00          VEHICLE - STOLEN     44  23.55
114884  2016      23:06:00  BATTERY - SIMPLE ASSAULT      1  23.56
114885  2016      23:06:00                  BURGLARY      2  23.56
114892  2016      23:07:00         THEFT OF IDENTITY      1  23.57
114899  2016      23:09:00  BATTERY - SIMPLE ASSAULT      7  23.59
114903  2016      23:09:00                  BURGLARY      6  23.59
114904  2016      23:09:00     BURGLARY FROM VEHICLE     19  23.59
114921  2016      23:09:00         THEFT OF IDENTITY     11  23.59
114927  2016      23:09:00          VEHICLE - STOLEN     22  23.59

[7273 rows x 5 columns]

In [137]:
df5.to_csv('Crime_Data_Top5.csv')